// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.github.sguzman.watch.protoc.store

@SerialVersionUID(0L)
final case class StoreCache(
    cache: scala.collection.immutable.Map[_root_.scala.Predef.String, com.github.sguzman.watch.protoc.store.AnimeUser] = scala.collection.immutable.Map.empty
    ) extends scalapb.GeneratedMessage with scalapb.Message[StoreCache] with scalapb.lenses.Updatable[StoreCache] {
    @transient
    private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
    private[this] def __computeSerializedValue(): _root_.scala.Int = {
      var __size = 0
      cache.foreach(cache => __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(com.github.sguzman.watch.protoc.store.StoreCache._typemapper_cache.toBase(cache).serializedSize) + com.github.sguzman.watch.protoc.store.StoreCache._typemapper_cache.toBase(cache).serializedSize)
      __size
    }
    final override def serializedSize: _root_.scala.Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
      cache.foreach { __v =>
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(com.github.sguzman.watch.protoc.store.StoreCache._typemapper_cache.toBase(__v).serializedSize)
        com.github.sguzman.watch.protoc.store.StoreCache._typemapper_cache.toBase(__v).writeTo(_output__)
      };
    }
    def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.github.sguzman.watch.protoc.store.StoreCache = {
      val __cache = (scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, com.github.sguzman.watch.protoc.store.AnimeUser] ++= this.cache)
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __cache += com.github.sguzman.watch.protoc.store.StoreCache._typemapper_cache.toCustom(_root_.scalapb.LiteParser.readMessage(_input__, com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry.defaultInstance))
          case tag => _input__.skipField(tag)
        }
      }
      com.github.sguzman.watch.protoc.store.StoreCache(
          cache = __cache.result()
      )
    }
    def clearCache = copy(cache = scala.collection.immutable.Map.empty)
    def addCache(__vs: (_root_.scala.Predef.String, com.github.sguzman.watch.protoc.store.AnimeUser)*): StoreCache = addAllCache(__vs)
    def addAllCache(__vs: TraversableOnce[(_root_.scala.Predef.String, com.github.sguzman.watch.protoc.store.AnimeUser)]): StoreCache = copy(cache = cache ++ __vs)
    def withCache(__v: scala.collection.immutable.Map[_root_.scala.Predef.String, com.github.sguzman.watch.protoc.store.AnimeUser]): StoreCache = copy(cache = __v)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => cache.map(com.github.sguzman.watch.protoc.store.StoreCache._typemapper_cache.toBase)(_root_.scala.collection.breakOut)
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(cache.map(com.github.sguzman.watch.protoc.store.StoreCache._typemapper_cache.toBase(_).toPMessage)(_root_.scala.collection.breakOut))
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.github.sguzman.watch.protoc.store.StoreCache
}

object StoreCache extends scalapb.GeneratedMessageCompanion[com.github.sguzman.watch.protoc.store.StoreCache] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.github.sguzman.watch.protoc.store.StoreCache] = this
  def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.github.sguzman.watch.protoc.store.StoreCache = {
    require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
    val __fields = javaDescriptor.getFields
    com.github.sguzman.watch.protoc.store.StoreCache(
      __fieldsMap.getOrElse(__fields.get(0), Nil).asInstanceOf[_root_.scala.collection.Seq[com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry]].map(com.github.sguzman.watch.protoc.store.StoreCache._typemapper_cache.toCustom)(_root_.scala.collection.breakOut)
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[com.github.sguzman.watch.protoc.store.StoreCache] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
      com.github.sguzman.watch.protoc.store.StoreCache(
        __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.collection.Seq[com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry]]).getOrElse(_root_.scala.collection.Seq.empty).map(com.github.sguzman.watch.protoc.store.StoreCache._typemapper_cache.toCustom)(_root_.scala.collection.breakOut)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = StoreProto.javaDescriptor.getMessageTypes.get(4)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = StoreProto.scalaDescriptor.messages(4)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq[_root_.scalapb.GeneratedMessageCompanion[_]](
    _root_.com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry
  )
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = com.github.sguzman.watch.protoc.store.StoreCache(
  )
  @SerialVersionUID(0L)
  final case class CacheEntry(
      key: _root_.scala.Predef.String = "",
      value: scala.Option[com.github.sguzman.watch.protoc.store.AnimeUser] = None
      ) extends scalapb.GeneratedMessage with scalapb.Message[CacheEntry] with scalapb.lenses.Updatable[CacheEntry] {
      @transient
      private[this] var __serializedSizeCachedValue: _root_.scala.Int = 0
      private[this] def __computeSerializedValue(): _root_.scala.Int = {
        var __size = 0
        if (key != "") { __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, key) }
        if (value.isDefined) { __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(value.get.serializedSize) + value.get.serializedSize }
        __size
      }
      final override def serializedSize: _root_.scala.Int = {
        var read = __serializedSizeCachedValue
        if (read == 0) {
          read = __computeSerializedValue()
          __serializedSizeCachedValue = read
        }
        read
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): Unit = {
        {
          val __v = key
          if (__v != "") {
            _output__.writeString(1, __v)
          }
        };
        value.foreach { __v =>
          _output__.writeTag(2, 2)
          _output__.writeUInt32NoTag(__v.serializedSize)
          __v.writeTo(_output__)
        };
      }
      def mergeFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry = {
        var __key = this.key
        var __value = this.value
        var _done__ = false
        while (!_done__) {
          val _tag__ = _input__.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case 10 =>
              __key = _input__.readString()
            case 18 =>
              __value = Option(_root_.scalapb.LiteParser.readMessage(_input__, __value.getOrElse(com.github.sguzman.watch.protoc.store.AnimeUser.defaultInstance)))
            case tag => _input__.skipField(tag)
          }
        }
        com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry(
            key = __key,
            value = __value
        )
      }
      def withKey(__v: _root_.scala.Predef.String): CacheEntry = copy(key = __v)
      def getValue: com.github.sguzman.watch.protoc.store.AnimeUser = value.getOrElse(com.github.sguzman.watch.protoc.store.AnimeUser.defaultInstance)
      def clearValue: CacheEntry = copy(value = None)
      def withValue(__v: com.github.sguzman.watch.protoc.store.AnimeUser): CacheEntry = copy(value = Option(__v))
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => value.orNull
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => value.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion = com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry
  }
  
  object CacheEntry extends scalapb.GeneratedMessageCompanion[com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry] = this
    def fromFieldsMap(__fieldsMap: scala.collection.immutable.Map[_root_.com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry = {
      require(__fieldsMap.keys.forall(_.getContainingType() == javaDescriptor), "FieldDescriptor does not match message type.")
      val __fields = javaDescriptor.getFields
      com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry(
        __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[_root_.scala.Predef.String],
        __fieldsMap.get(__fields.get(1)).asInstanceOf[scala.Option[com.github.sguzman.watch.protoc.store.AnimeUser]]
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        require(__fieldsMap.keys.forall(_.containingMessage == scalaDescriptor), "FieldDescriptor does not match message type.")
        com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry(
          __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[scala.Option[com.github.sguzman.watch.protoc.store.AnimeUser]])
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = com.github.sguzman.watch.protoc.store.StoreCache.javaDescriptor.getNestedTypes.get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = com.github.sguzman.watch.protoc.store.StoreCache.scalaDescriptor.nestedMessages(0)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
      var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
      (__number: @_root_.scala.unchecked) match {
        case 2 => __out = com.github.sguzman.watch.protoc.store.AnimeUser
      }
      __out
    }
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry(
    )
    implicit class CacheEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, com.github.sguzman.watch.protoc.store.AnimeUser] = field(_.getValue)((c_, f_) => c_.copy(value = Option(f_)))
      def optionalValue: _root_.scalapb.lenses.Lens[UpperPB, scala.Option[com.github.sguzman.watch.protoc.store.AnimeUser]] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry, (_root_.scala.Predef.String, com.github.sguzman.watch.protoc.store.AnimeUser)] =
      _root_.scalapb.TypeMapper[com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry, (_root_.scala.Predef.String, com.github.sguzman.watch.protoc.store.AnimeUser)](__m => (__m.key, __m.getValue))(__p => com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry(__p._1, Some(__p._2)))
  }
  
  implicit class StoreCacheLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, com.github.sguzman.watch.protoc.store.StoreCache]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, com.github.sguzman.watch.protoc.store.StoreCache](_l) {
    def cache: _root_.scalapb.lenses.Lens[UpperPB, scala.collection.immutable.Map[_root_.scala.Predef.String, com.github.sguzman.watch.protoc.store.AnimeUser]] = field(_.cache)((c_, f_) => c_.copy(cache = f_))
  }
  final val CACHE_FIELD_NUMBER = 1
  @transient
  private val _typemapper_cache: _root_.scalapb.TypeMapper[com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry, (_root_.scala.Predef.String, com.github.sguzman.watch.protoc.store.AnimeUser)] = implicitly[_root_.scalapb.TypeMapper[com.github.sguzman.watch.protoc.store.StoreCache.CacheEntry, (_root_.scala.Predef.String, com.github.sguzman.watch.protoc.store.AnimeUser)]]
}
